### ISSUE TITLE
User Login and Signup

### ISSUE THREAD

**Issue by mwakuni** [mkaomwakuni/Hao_Fiti#21]
**Objective:**

- Develop a user authentication feature that allows new users to sign up and existing users to log in to the app.

**Signup Functionality:**

- Create a signup screen where new users can register using their email address and password.
- Implement form validation to ensure valid input (e.g., valid email format, password strength).
- Display error messages for invalid inputs.
- Ensure secure password handling (e.g., password hashing before storing).

**Login Functionality:**

- Create a login screen for existing users to sign in using their registered email and password.
- Implement "Forgot Password" functionality that allows users to reset their password.
- Provide form validation for login inputs.

**Backend Integration:**

- Connects the login and signup functionality to the Auth service via Firebase Authentication.

**Comment by imkao0** [comment]
All set
